version: '3.1'

services:

  db:
    build: sql
    restart: always
    ports:
      - 3306:3306

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./synchweb:/synchweb
      # - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    # image: php:5-fpm
    build: php_with_mysqli
    volumes:
      - ./synchweb:/synchweb

    # environment:
    #   MYSQL_ROOT_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080